# Generated by Django 4.0.6 on 2022-09-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('NOVEL', 'NOVEL'), ('DRAMA', 'DRAMA'), ('STORY', 'STORY'), ('FICTION', 'FICTION'), ('MOTIVATIONAL', 'MOTIVATIONAL')], max_length=100),
        ),
    ]
